// Code generated by go-bindata.
// sources:
// ../static/css/style.css
// ../tmpl/index.tmpl
// DO NOT EDIT!

package resources

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _staticCssStyleCss = []byte("\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\xbc\x93\xdd\x8e\x9b\x30\x10\x85\xaf\x37\x52\xde\x61\xa4\xaa\x52\x22\xe1\x88\x90\xb0\xdb\xf5\x3e\x8d\xc1\x83\xb1\x6a\x3c\xc8\x78\xbb\xac\xaa\xbe\x7b\xfd\x13\x94\x84\xb4\xea\x5d\x2f\xcc\x05\x73\x3c\xfe\x8e\x8f\xa7\x21\xf9\x09\x3f\xb7\x9b\xa7\x46\xb4\xdf\x95\xa3\x77\x2b\x39\x38\xd5\xec\x4e\x2f\x05\xc4\x75\x7e\xd9\xbf\x85\x72\x4b\x86\x5c\xae\x54\xa7\xba\x80\xea\xfc\x1a\x3e\x75\x1d\x8b\x00\x1d\x59\xcf\x3a\x31\x68\xf3\xc9\x61\x20\x4b\xd3\x28\x5a\x0c\xa5\x5f\xdb\xcd\x76\xf3\xa5\x47\x21\xd1\xa5\x63\x3c\xce\x9e\x09\xa3\x95\xe5\xd0\xa2\xf5\xe8\x62\xf7\x86\x5c\x10\x70\x38\x8e\x33\x4c\x64\xb4\x84\xc6\x04\x9e\x6b\x89\x39\x21\xf5\xfb\x14\x14\xf5\x38\xbf\xad\x70\x8d\xb6\x28\x1c\x53\x51\x13\x5a\xee\x12\xfe\x73\xc0\x0f\xab\x7e\xde\x17\x89\xfa\x78\x2a\x20\xad\xd7\x7d\x32\x44\x3f\xd0\x75\x86\x3e\x38\xf4\x5a\x4a\xb4\x0b\xec\x21\x76\x1d\x59\x46\x2e\xe0\x80\x33\xba\x56\x4f\xc8\xae\x26\x00\xfe\xce\xbb\xd4\xd6\xc0\x00\xa3\x90\x52\x5b\xc5\xa1\x84\x63\x99\x4d\x0c\xc2\x29\x6d\x99\xa7\xf1\x7f\x1b\x83\xc3\xe8\x48\x39\x9c\xa6\x6c\x08\xe0\xc2\x62\xb0\xf3\x1c\xd8\x85\x30\x6f\x5c\x5f\x41\x7f\x4a\x51\x86\x43\x44\xd0\xc6\x1d\x8f\xd2\xdb\xf6\x8b\xd2\x69\xd5\xfb\x15\x8e\xd1\x93\xcf\xef\xef\x9f\x4f\x20\x5d\x93\x25\x8b\x37\xff\x1a\xf2\x9e\x06\x96\x3a\x3f\xbe\x91\x3b\x4d\xe4\x7c\x90\xdc\x26\xc0\x96\x9f\x97\xa4\xee\x72\xc9\xcc\x77\xae\x56\x13\x23\x76\xc7\xaa\x0c\x33\x51\x9e\xd3\x60\x14\x50\x1e\xaa\x32\x25\xd2\x63\xc4\xe3\x7f\x8c\x7d\xb9\xe9\xa7\x0f\x2d\x7d\xcf\xa1\xfa\xf6\x35\x9f\xf6\x3b\x00\x00\xff\xff\xca\x1d\xb7\x0f\x99\x03\x00\x00")

func staticCssStyleCssBytes() ([]byte, error) {
	return bindataRead(
		_staticCssStyleCss,
		"static/css/style.css",
	)
}

func staticCssStyleCss() (*asset, error) {
	bytes, err := staticCssStyleCssBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "static/css/style.css", size: 921, mode: os.FileMode(438), modTime: time.Unix(1461524386, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _tmplIndexTmpl = []byte("\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\x8c\x53\xc1\x6e\xdc\x20\x10\x3d\xa7\x52\xff\x81\x22\x55\x6a\x0f\x59\x2b\x9b\x4b\xd5\x62\x1f\x9a\x46\xbd\xb5\xab\x28\x97\x1e\x29\xcc\xae\xd1\x62\x58\xc1\x24\x4d\x84\xfc\xef\x05\x1b\x3b\xb8\x6b\xa9\x39\x79\xe0\xcd\x3c\xde\x7b\x18\xf6\xee\xdb\xcf\x9b\xfb\x5f\xbb\x5b\xd2\x62\xa7\x9b\xb7\x6f\x58\xfe\x5e\xb0\x16\xb8\x4c\xc5\x05\xeb\x00\x39\x11\x2d\x77\x1e\xb0\xa6\x0f\xb8\xbf\xfc\x44\x47\x04\x15\x6a\x68\x6e\xac\x79\x54\x02\x49\xfc\x4a\x85\xca\x1a\x65\x0e\xe4\xde\x71\x71\x04\xc7\xaa\xb1\x67\x68\xd7\xca\x1c\x49\xeb\x60\x5f\xd3\xca\x23\x47\x25\x2a\xe1\x7d\x2c\x9f\x35\x6c\x62\x45\x89\x03\x5d\xd3\x61\xed\x5b\x00\x1c\x8e\x61\xd5\x24\x85\xfd\xb6\xf2\x79\xa4\x92\xea\x91\x28\x59\xd3\x04\x81\x1b\xe5\x44\xcd\x57\xcd\x1d\x37\xc7\x38\x71\x95\x77\x52\x9f\xd0\xdc\xfb\x9a\x9e\x9c\x3d\x38\x88\xa7\x34\xac\x8a\xdb\x23\xcf\x4b\x35\x31\x0a\x6b\x10\x0c\x66\xca\x10\x1c\x37\x07\x20\x9b\xef\xce\x3e\x9c\x7c\xdf\x9f\xd1\x1e\x12\x90\xbb\xcf\x81\xcb\x85\xc0\x24\x71\xdb\x84\xb0\xf9\xc1\x3b\xe8\xfb\xa8\x73\x3b\x03\x6b\x4a\xc9\x10\x45\x4d\xff\x28\x89\xed\x67\x12\xc2\xc0\xb9\xcb\x30\xc9\x34\xef\xbf\x94\x96\x4a\x53\x6b\x82\xb4\xf2\x38\xcb\x99\xed\xdd\x3e\x81\x13\xca\xc3\xe4\x70\x39\x09\x19\x9d\xe7\x56\xd1\x7f\xbd\x26\xb7\xd7\x0b\xb7\xd7\x05\xb4\x46\xf0\x72\x45\x71\xea\x2b\x78\xec\xfb\x2a\x84\x0f\xca\x48\x78\x8a\x57\x60\xb9\xf6\x64\xfb\x71\x73\x07\xe9\x26\x4a\x9b\xaf\x0e\x70\x3a\xea\x7f\x19\x2e\x53\x5c\xb2\x4b\xf0\xc2\xa9\x53\xfa\xd3\x0b\xaf\x51\xf1\x0e\xdc\xde\xba\x8e\x1b\x01\x73\x8c\x4b\x9e\xc5\x22\xaa\x31\x72\x6a\x2c\x90\xa2\x2c\x5a\xe6\x5d\x56\xe5\x67\x10\x03\x1d\x1f\xeb\xdf\x00\x00\x00\xff\xff\x51\x10\x3d\x26\xc6\x03\x00\x00")

func tmplIndexTmplBytes() ([]byte, error) {
	return bindataRead(
		_tmplIndexTmpl,
		"tmpl/index.tmpl",
	)
}

func tmplIndexTmpl() (*asset, error) {
	bytes, err := tmplIndexTmplBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "tmpl/index.tmpl", size: 966, mode: os.FileMode(438), modTime: time.Unix(1461523883, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"static/css/style.css": staticCssStyleCss,
	"tmpl/index.tmpl": tmplIndexTmpl,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"static": &bintree{nil, map[string]*bintree{
		"css": &bintree{nil, map[string]*bintree{
			"style.css": &bintree{staticCssStyleCss, map[string]*bintree{}},
		}},
	}},
	"tmpl": &bintree{nil, map[string]*bintree{
		"index.tmpl": &bintree{tmplIndexTmpl, map[string]*bintree{}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

